AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for a websockets sendmessage.

  '
Globals:
  Function:
    Timeout: 200
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: icon_cognito_auth_cognito_user_pool
      LambdaConfig:
        PreSignUp:
          Fn::GetAtt:
          - PreSignupLambdaFunction
          - Arn
        PostConfirmation:
          Fn::GetAtt:
          - PostConfirmationLambdaFunction
          - Arn
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
      - email
      Schema:
      - Name: name
        Required: true
        AttributeDataType: String
      - Name: company
        Mutable: true
        Required: false
        AttributeDataType: String
        StringAttributeConstraints:
          MinLength: 1
          MaxLength: 256
      - Name: usrl
        Mutable: true
        Required: false
        AttributeDataType: Number
  PreSignupLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://euc-test-brasil/314c983f157ba6a934890a29119d282a
      Handler: handler.lambda_handler
      MemorySize: 256
      Runtime: python3.7
      Timeout: 15
  PostConfirmationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://euc-test-brasil/314c983f157ba6a934890a29119d282a
      Handler: handler.change_user_group
      MemorySize: 256
      Runtime: python3.7
      Timeout: 3
      Environment:
        Variables:
          ZERO: Operator
          ONE: Supervisor
          TABLE_NAME:
            Ref: UsersTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UsersTable
      - Statement:
        - Effect: Allow
          Action: cognito-idp:*
          Resource: '*'
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true
  PreSignupLambdaFunctionExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - PreSignupLambdaFunction
        - Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::Sub: arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}
  PostConfirmationLambdaFunctionExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - PostConfirmationLambdaFunction
        - Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::Sub: arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sam_cognito_auth_cognito_client
      UserPoolId:
        Ref: CognitoUserPool
  UserPoolGroupAdmins:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Admin
      UserPoolId:
        Ref: CognitoUserPool
  UserPoolGroupOperator:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Operator
      UserPoolId:
        Ref: CognitoUserPool
  UserPoolGroupSupervisor:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Supervisor
      UserPoolId:
        Ref: CognitoUserPool
Outputs:
  ConnectionsTableArn:
    Description: Connections table ARN
    Value:
      Fn::GetAtt:
      - ConnectionsTable
      - Arn
  OnConnectFunctionArn:
    Description: OnConnect function ARN
    Value:
      Fn::GetAtt:
      - OnConnectFunction
      - Arn
  SendMessageFunctionArn:
    Description: SendMessage function ARN
    Value:
      Fn::GetAtt:
      - SendMessageFunction
      - Arn
